const bugabooInsights = {
  "archaeognatha": {
    commonName: "Jumping Bristletails",
 vibe: "Feeling ancient and primitive while everyone else seems evolved. Like you're surprisingly effective despite using outdated methods. Having hidden agility that catches people completely off guard.",
    quotes: [
      "Wings? Who needs them when you've got that arch-and-launch technique perfected before flight was even invented? You're not behind the times, darling. You're the original prototype everyone else copied.",
      "Listen, some creatures need fancy wings and compound eyes to impress. You? You just bend backwards and boing. Instant scene-stealer. That's what 400 million years of practice gets you.",
      "They call you primitive? Tell them you prefer 'successfully unchanged since the Devonian.' It's like wearing the same perfect outfit for millennia because you nailed it the first time.",
      "You know what's cooler than being cutting-edge? Being the edge that never needed cutting. Keep jumping, you magnificent fossil. You're proof that some designs are too good to update.",
      "Sure, everyone else evolved wings, but you stuck with your core competency: surprising the hell out of predators with that backwards somersault. Innovation isn't always about adding features, love.",
      "Rocky coastlines and ancient genes. You're basically the geological formation of the natural world. Solid, enduring, and occasionally capable of spectacular acrobatics. What's not to admire?",
      "Feeling outdated? Sweetheart, you're not old news. You're pre-news. You were jumping before jumping was cool, before cool was even a concept, before concepts needed brains to think them.",
      "Your body plan is so fundamental, it's basically natural architecture 101. Everyone else just added unnecessary renovations. You're the original tiny home: efficient, mobile, and timelessly stylish.",
      "They evolved wings and you thought, 'Nah, I'm good.' That's not primitive. That's knowing yourself so well you don't need to follow trends. Your confidence predates confidence.",
      "Being a living fossil means you've seen every trend come and go while you kept doing your springy thing. You're not stuck in the past; the past was stuck on your perfect design.",
      "Some creatures fly, some crawl, but you? You've turned gravity into your personal trampoline using nothing but good old-fashioned body mechanics. That's not primitive. That's physics mastery.",
      "You're the equivalent of a perfectly seasoned cast-iron pan: simple, indestructible, and getting better with age. Let the non-stick newbies have their moment; you'll outlast them all.",
      "Coastal rocks and ancient vibes? You're basically the wise hermit of the natural world, except instead of dispensing wisdom from a mountaintop, you do backflips. Much more entertaining.",
      "Your jumping technique is older than most mountain ranges. When people call you old-fashioned, remind them that fashions cycle back, but you never left in the first place.",
      "Wings are just peer pressure with feathers. You said 'thanks but no thanks' 400 million years ago and have been crushing it ever since. That's not primitive, love. That's principled."
    ]
  },
  "zygentoma": {
    commonName: "Silverfish",
vibe: "Feeling like you're stuck in old patterns while everyone else moves forward. Drawn to comfort zones that others might judge as \"settling.\" Like you're sneaking around the edges instead of taking center stage.",
    quotes: [
      "So you nibble a bit of wallpaper when nobody's looking. Who among us hasn't consumed questionable content in the dark? You're just more literal about it, you silvery little rebel.",
      "Four hundred million years and you still know the best seat in the house: that cozy spot behind the bathroom radiator. You're not hiding, darling. You're luxuriating.",
      "They call it 'damage' when you eat their first editions, but I call it performance art. You're literally digesting knowledge, turning paper into purpose. Very meta of you.",
      "Found in the shower? More like a spa enthusiast who discovered steam rooms before vertebrates discovered spines. Your self-care routine predates the concept of self.",
      "You know what's cooler than wings? Knowing exactly where every warm, humid corner in a house is located. You're not primitive. You're a comfort cartographer with millions of years of experience.",
      "Dancing through shadows at 3 AM, leaving little silver calling cards. You're not a pest, you're a nocturnal artist working in the medium of mysterious appearances.",
      "Some creatures need daylight to shine. You? You shimmer in darkness like a tiny disco ball that predates disco by several geological eras. Own that bathroom glamour, love.",
      "You've been seeking out the coziest spots since before cozy was invented. That's not opportunistic. That's being a trendsetter who's so far ahead, everyone thinks you're behind.",
      "Eating glue and loving it? That's not weird, that's knowing your brand. You were organic and gluten-aware before it was fashionable. Just maybe leave the photo albums alone?",
      "Your scales catch light like tiny mirrors reflecting 400 million years of 'I know what I like and I like it damp.' That's not stubborn. That's spectacular self-knowledge.",
      "Bathroom aficionado? Please. You're a moisture sommelier, a humidity historian, a steam-room sage. You don't have issues, you have preferences, ancient and unshakeable.",
      "Racing across bathroom tiles at midnight? You're not fleeing, you're doing your cardio. After 400 million years, you've learned the importance of staying quick on your six little feet.",
      "You eat books but never learned to read? That's because you're absorbing stories through your whole being, you mystical little librarian. Just maybe stick to the paperbacks?",
      "They put out traps, but you just shimmy around them with prehistoric pizzazz. You're not a survivor, you're a thriver, turning their bathrooms into your personal speakeasy.",
      "Wingless and wonderful, you prove that evolution isn't about adding features. It's about perfecting your niche. And your niche just happens to be everyone else's neglected corners. You're loved, you shimmering shadow-dancer."
    ]
  },
  "ephemeroptera": {
    commonName: "Mayflies",
vibe: "Time feels like it's running out before you've made your mark. Living so intensely it's almost overwhelming and unsustainable. Like your window of opportunity is beautiful but terrifyingly brief.",
    quotes: [
      "Twenty-four hours to live and you're spending it dancing above water? That's not desperate, love. That's knowing your priorities. Some get decades to be mediocre; you get a day to be magnificent.",
      "Who needs a mouth when you're too busy being gorgeous? You literally can't eat because you're built purely for passion. That's not a design flaw, that's commitment to the cause.",
      "Spent years underwater preparing for this moment? You're not procrastinating, you're the ultimate method actor. All that time was just rehearsal for your standing ovation finale.",
      "Your entire adult life is shorter than most Netflix episodes, yet somehow you're more memorable than entire seasons. Quality over quantity, darling. You're the haiku of existence.",
      "Synchronized emergence? You're not following the crowd, you're creating the most epic flash mob nature has ever seen. When you party, the whole river knows about it.",
      "Those upright wings aren't just for show. They're victory flags declaring 'I MADE IT!' after years of underwater prep work. Every moment airborne is a celebration, not a countdown.",
      "Can't eat, won't eat, too busy creating the next generation? You're not starving, you're focused. Some multitask; you're pure, undiluted purpose with wings.",
      "A thousand of you dancing in the sunset, living your entire adult life in one glorious evening? That's not tragic. That's the most beautiful rave nature ever invented.",
      "Your tail filaments trail behind you like the universe's shortest comet. Brief? Yes. Brilliant? Absolutely. You're not a shooting star, you're the whole meteor shower.",
      "Born this morning, gone by nightfall, but those few hours? Chef's kiss. You're living proof that a life's worth isn't measured in length but in how spectacularly you shine.",
      "Years as a nymph, hours as an adult. You're basically the equivalent of saving up all your vacation days for one absolutely legendary weekend. Time well spent!",
      "They say you're ephemeral, but ephemeral things—sunsets, laughter, first kisses—those are what we remember forever. You're not temporary; you're concentrated eternity.",
      "No mouth, no problem. You're too busy making love and making waves to worry about making dinner. That's not limitation, that's laser focus on what truly matters.",
      "Your entire species emerges together because why live your best life alone? You're not just seizing the day, you're throwing it a party and inviting everyone you know.",
      "One perfect day to find love, create life, and dance yourself into legend? Some get a century and do less. You're not rushed, darling, you're efficient. Fabulously, gloriously efficient."
    ]
  },
  "odonata": {
    commonName: "Dragonflies & Damselflies",
vibe: "Needing clarity but your thoughts keep darting in every direction. Feeling powerful but scattered, like you can't focus that energy properly. Seeing too many angles and possibilities to make a clear decision.",
    quotes: [
      "Thirty thousand lenses in each eye and you're worried about missing something? Darling, you don't have blind spots. You have a 360-degree IMAX theater of possibility. Pick your favorite show and dive in.",
      "Flying backwards while everyone else struggles forward? That's not showing off, that's having options. You're the only one at the party who can moonwalk through the air. Use it.",
      "Spent your youth underwater hunting like a tiny kraken, now you're an aerial assassin? You're not having an identity crisis, you're a masterclass in career pivots. Own both résumés.",
      "Those wings aren't just iridescent. They're broadcasting your mood in technicolor. You're not indecisive, you're a flying kaleidoscope showing the world every brilliant angle of you.",
      "Hovering in place while the world rushes by? That's not procrastination, love. That's having the processing power to actually think before you strike. Stillness is your superpower.",
      "Can catch a mosquito mid-flight but can't decide what you want for dinner? Welcome to having prehistoric reflexes and modern problems. Your ancestors are proud, even if you're not.",
      "Delicate or dynamic, either way, you're engineering perfection with wings. Some crawl toward their dreams; you can approach yours from literally any direction.",
      "Those ancient eyes see ultraviolet, polarized light, and probably your ex's bad intentions from three meadows away. You're not paranoid, you're panoramic.",
      "Darting here, zipping there, hovering everywhere? You're not scattered, you're sampling the entire buffet of life with the efficiency of a million years of evolution. Taste it all.",
      "Born to hunt, built to dazzle, designed to make helicopters jealous. You're not extra, you're exactly the right amount of spectacular for someone who can fly in reverse.",
      "Your wings beat so fast they're practically invisible, yet somehow everyone notices when you arrive. That's not contradiction, that's presence, darling. Subtle as a rainbow, powerful as thunder.",
      "Feeling torn between your aquatic past and aerial present? Stop choosing. You're the ultimate amphibious success story. Not everyone can say they've conquered two elements before lunch.",
      "They say you symbolize change, but really you symbolize mastery. Anyone can transform; you transformed and then learned to fly backwards about it. That's next-level.",
      "Your compound eyes see motion before it happens, colors humans can't imagine, and still you sometimes crash into windows. Perfection is overrated. You're beautifully, powerfully real.",
      "Swift changes coming? Please. You can accelerate from zero to zoom in a heartbeat, brake mid-air, and pivot on a dewdrop. Change isn't your challenge, it's your dance floor."
    ]
  },
  "plecoptera": {
    commonName: "Stoneflies",
vibe: "Like you can only thrive under perfect conditions that rarely exist. Too sensitive for this harsh world, easily overwhelmed by chaos. Feeling fragile and vulnerable when things get rough around you.",
    quotes: [
      "Can't survive in polluted water? That's not fragile, love. That's having a palate so refined you're basically a water sommelier. Your body is a five-star review system for river quality.",
      "Weak flier? Who cares when you've mastered the art of stream-side strolling. Some need to show off in the air; you're confident enough to keep it grounded. Literally.",
      "Your presence means the water's clean, your absence means trouble's brewing. You're not just living your life, you're a walking environmental report card. That's power, darling.",
      "Drumming your abdomen to communicate? While others scream, you're tapping out morse code love poems on river rocks. Subtle, sophisticated, and impossibly cool.",
      "Drab colored? Please. You're not boring, you're river camouflage couture. Blending in when you're literally the gold standard of water quality? That's not plain, that's ironic.",
      "Some eat everything, go everywhere, survive anything. You? You only show up for the good stuff. That's not limitation, that's knowing your worth.",
      "Those two tail filaments aren't just for show. They're like divining rods for finding the purest water. You're not picky, you're a quality control specialist with millions of years experience.",
      "Scientists literally use you to measure ecosystem health. You're not sensitive, you're calibrated to perfection. The world needs your kind of honesty.",
      "Adults that don't eat? You're too busy making sure the next generation gets the same pristine waters you enjoyed. That's not sacrifice, that's legacy thinking.",
      "Needing fast, cool, oxygen-rich water isn't high maintenance. It's having standards. You're the friend who won't settle for gas station coffee when there's a proper café nearby.",
      "Your sensitivity to pollution makes you an early warning system with wings. You're not delicate, you're diagnostic. Your feelings are literally scientific data.",
      "Some are generalists; you're a specialist in excellence. Your whole existence whispers 'this place is good' or shouts 'time to clean up!' That's not weakness, that's wisdom.",
      "Belly-drumming your feelings instead of buzzing about them? You're the introvert who communicates through quality, not quantity. Every tap says what others need paragraphs to express.",
      "Your young spend years preparing underwater, emerging only when conditions are perfect. That's not hesitation, that's knowing that good things come to those who wait for clean water.",
      "They say you're an indicator species, but really you're a truth-teller. In a world full of creatures that'll tolerate anything, you're brave enough to demand better. Keep those standards high, you pristine little prophet."
    ]
  },
  "embioptera": {
    commonName: "Webspinners & Footspinners",
vibe: "Hiding away in your comfort zone while life happens outside. Too shy or reclusive to put yourself out there properly. Like you need to control every detail of your environment to feel safe.",
    quotes: [
      "Silk glands in your feet? While others talk about walking the walk, you're literally spinning luxury with every step. That's not hiding, that's living in a self-made masterpiece.",
      "Running backwards through your silk tunnels faster than most run forward? You're not retreating, darling. You're just facing your past while your feet build your future.",
      "Some need wings to feel free. You? You've got an entire silk highway system you built yourself. That's not limitation, that's infrastructure.",
      "Your home isn't just where your heart is. It's where your feet have literally woven your dreams into reality. Every thread says 'I chose this, I made this, I love this.'",
      "Colonial but selective? You're not antisocial, you're a bouncer at your own exclusive silk speakeasy. Only the cool kids know the secret tunnel entrance.",
      "Females don't need wings when they've architected paradise. Why fly away from perfection? You're not grounded, you're established, with a silk-lined mortgage to prove it.",
      "Those silk galleries aren't just tunnels. They're a nervous system you've externalized, a web of 'me' that says 'this far and no farther.' That's not anxiety, that's boundaries made beautiful.",
      "Spinning comfort with your toes while others chase it with their wings? You're not missing out. You're the only one who figured out happiness is homemade. Literally.",
      "Your maternal care includes providing silk-lined nurseries? You're not a helicopter parent, you're a luxury resort developer specializing in newborn comfort. Five stars on Yelp.",
      "Reluctant to leave your galleries? Why would you? You've built the equivalent of a temperature-controlled, silk-sheeted, perfectly lit bunker. That's not fear, that's good taste.",
      "Males fly away to find love, but females stay put and let love find them. You're not passive, you're confident your silk palace speaks for itself. Location, location, location.",
      "Your whole colony lives in connected silk tunnels? That's not codependency, that's the original social network, where everyone's verified and the trolls can't find the entrance.",
      "Backwards-running tunnel specialist? You're playing 3D chess while others play checkers. Every direction is forward when you built the whole game board yourself.",
      "Some eat their homes, you wear yours. Those silk threads aren't prison bars, they're the softest security system ever invented, and you're the architect, guard, and VIP guest.",
      "Creating your own microclimate of warm, humid perfection? You're not high-maintenance, you're a comfort engineer who refuses to compromise. Your feet literally weave self-care into existence."
    ]
  },
  "zoraptera": {
    commonName: "Angel Insects",
vibe: "Feeling invisible and overlooked despite having so much to offer. Like your simple approach gets dismissed in a flashy world. Undervalued and unnoticed, even though you know you matter.",
    quotes: [
      "Three millimeters of mystery wrapped in angel white? You're not invisible, you're selective viewing. Some perform for crowds; you're a private screening for the universe's most attentive audience.",
      "Living in sawdust and dining on fungal spores? That's not humble, that's knowing exactly which microscopic miracles matter. You're proof that heaven operates on a very small scale.",
      "Angel beings who shed their wings after finding home? You're not giving up flight, you're choosing depth over distance. Sometimes paradise is under a really good log.",
      "They had to name you after angels because 'tiny pale perfection that minds its own business' was too long for the textbooks. Your whole existence is an understatement.",
      "So secretive that science barely knows you exist? You're not overlooked, you're exclusive. The universe's best-kept secrets always come in the smallest packages.",
      "Your colonies are so hidden, finding you is like discovering a secret monastery of miniature monks. Except instead of prayers, you're recycling dead wood into life. Same energy, different altar.",
      "Primitive? Please. You're so evolved you realized fame was overrated before anyone invented it. Living your best life in decomposing privacy since before privacy was cool.",
      "Those wings you shed? They're not lost, they're your calling cards, tiny proof that angels visited and decided to stay. You don't fall from grace; you settle into it.",
      "Feeding on spores and tiny arthropods in the dark? You're not a scavenger, you're a microscopic guardian angel of the decomposition cycle. Someone has to bless the forgotten spaces.",
      "At 2mm tall, you're basically a living whisper of divinity. Some angels blow trumpets; you prefer to hum quietly while converting dead trees into tomorrow's forest floor.",
      "They call you primitive but you live in communes, share resources, and know when to let go of things that no longer serve you (like wings). You're not behind, you're enlightened.",
      "Your pale appearance isn't lack of color. It's all colors reflected back, too pure to absorb any single shade. You're not plain; you're prism-white possibility.",
      "Unknown, unnamed, unnoticed by most? Perfect. You're not missing recognition, you're missing the exhaustion of being recognized. Your anonymity is your superpower.",
      "Living with termites sometimes? You're not freeloading, you're the mysterious neighbor who keeps to themselves but somehow makes the whole building feel blessed. Subtle influence is still influence.",
      "So tiny that most people never know you exist, yet you're quietly essential to the ecosystem? Darling, that's not insignificance, that's being too important for publicity. You're heaven's best-kept secret, operating on a need-to-know basis."
    ]
  },
  "dermaptera": {
    commonName: "Earwigs",
vibe: "Misunderstood because of your intimidating exterior or bad reputation. Feeling defensive and protective but coming across as aggressive. Like people judge you harshly without seeing your caring heart.",
    quotes: [
      "Those pincers that make everyone nervous? They're basically nature's multi-tool: part baby-bouncer, part fungus-fighter, part 'back off' billboard. You're not scary, you're prepared.",
      "Cleaning each egg individually to prevent mold? Most lay 'em and leave 'em, but you're over here running a five-star nursery with daily housekeeping. That's not extra, that's excellence.",
      "Named after a medieval myth about crawling in ears? Honey, you're more interested in tending your babies than terrorizing humans. You're not a horror story, you're a love story with pincers.",
      "Those cerci can fold wings more complex than origami, yet everyone focuses on how they look 'menacing.' You're not threatening, you're a transformer with a heart of gold.",
      "Hiding in damp crevices by day, fierce parent by night? You're not creepy, you're Clark Kent with six legs and a much better childcare plan.",
      "Your pincers say 'don't touch' but your parenting says 'I'll die for these babies.' That's not contradiction, that's the most honest advertising in nature.",
      "Guarding your eggs for weeks while others abandon theirs in seconds? You're not clingy, you're revolutionary. Single parenting with pincers and panache.",
      "Those fan-wings folded under your shell? Hidden beauty beneath a tough exterior. You're basically the equivalent of a leather-jacketed poet. Soft verses, hard cover.",
      "Nocturnal caregiver with built-in defense weapons? You're not a nightmare, you're every baby's dream parent. Mary Poppins wishes she had your equipment.",
      "They spread lies about you crawling in ears, meanwhile you're too busy giving your actual babies piggyback rides. You're not misunderstood, you're slandered, and still too classy to care.",
      "Using those same pincers for courtship and childcare? That's range, darling. From 'hello, gorgeous' to 'eat your vegetables', you've got every life stage covered.",
      "Your maternal care is so unusual for solitary creatures that scientists had to double-check. You're not following the rules, you're rewriting them with those magnificent cerci.",
      "Tough enough to survive anywhere, tender enough to individually wash eggs? You're not having an identity crisis, you're having it all. Fierce and gentle aren't opposites in your world.",
      "Those pincers everyone fears are the same ones that gently arrange your eggs and corral wandering nymphs. You're not dangerous, you're a Swiss Army knife of love.",
      "Living proof that the best parents often look the scariest to everyone else? Your intimidation factor is just your love turned outward. Nobody messes with your babies, and that's not creepy, that's goals."
    ]
  },
  "orthoptera": {
    commonName: "Grasshoppers & Crickets & Katydids",
vibe: "Frustrated because your voice isn't being heard above the noise. Restless and impatient, like you need to make a big move soon. Bursting with something authentic that demands expression.",
    quotes: [
      "Rubbing your legs together to make music? That's not weird, that's turning your whole body into a violin. Mozart had a piano; you ARE the instrument. Play on, you magnificent six-legged symphony.",
      "Those hind legs aren't just for hopping, they're launch pads for your dreams. Some crawl toward success; you're built to quantum leap over the competition.",
      "Keeping everyone up at night with your song? You're not an insomniac, you're a midnight DJ broadcasting love songs to the universe. Your bedroom is a recording studio.",
      "Disguised as a leaf but singing like a rock star? That's not identity confusion, that's being incognito fabulous. Even your camouflage has a soundtrack.",
      "Temperature affects your chirp rate? Congratulations, you're a living thermometer with rhythm. You don't just feel the heat, you sing it into existence.",
      "In the sun, ready to jump? You're not restless, you're solar-powered potential energy with legs. Every sunny day is your personal launch window.",
      "Your love song can be heard a mile away? That's not desperate, that's confident. You know your worth and you're broadcasting it in surround sound. Let them come to you.",
      "Those powerful legs can launch you twenty times your body length? You're not showing off, you're defying physics with style. NASA wishes they had your thrust-to-weight ratio.",
      "Serenading from underground? You're not hiding, you're the earth's own subwoofer, making the whole ground vibrate with your truth.",
      "Different songs for love, war, and warning? You're not noisy, you're multilingual in music. Your legs speak fluent emotion with a percussion section.",
      "Incomplete metamorphosis means you're born almost ready to rock? You don't need a cocoon glow-up. You came out of the egg with your instruments tuned and ready.",
      "Summer wouldn't sound like summer without you? That's not coincidence, that's job security. You're the seasonal soundtrack everyone waits for. Own that cultural relevance.",
      "Feeling the urge to leap before you look? Your legs are smarter than your fear. They've calculated the physics while your brain's still debating. Trust the spring-loaded wisdom.",
      "They keep you in cages for luck in some cultures? That's because your song is literally hope with a beat. You're not a prisoner, you're a portable blessing machine.",
      "Male? Female? Who cares. Everyone can make some kind of music. You're the most egalitarian orchestra in nature. Every voice matters, every leap counts, every song adds to the symphony."
    ]
  },
  "phasmatodea": {
    commonName: "Stick Insects & Leaf Insects & Walking Sticks",
vibe: "Feeling invisible and overlooked, like you blend into the background. Too patient for your own good while opportunities pass you by. Underestimated because your quiet nature gets mistaken for weakness.",
    quotes: [
      "Six inches long and nobody noticed you at the party? That's not invisibility, love. That's selective revelation. You're not wallpaper; you're a secret masterpiece waiting for someone worthy of the viewing.",
      "Swaying gently to mimic the breeze? You're not indecisive, you're so committed to your craft that you method-act as foliage. Daniel Day-Lewis wishes he had your dedication.",
      "Lost a leg and growing it back? While others fall apart, you're literally pulling yourself together. That's not recovery, that's upgrade culture at its finest.",
      "Reproducing without males? You're not lonely, you're self-sufficient. Who needs dinner and a movie when you can clone yourself and call it a day? Ultimate independence.",
      "They walk right past you, mistaking you for decor? Perfect. You're gathering intelligence while they're revealing secrets. You're not overlooked, you're undercover.",
      "Nocturnal vegetarian who looks like salad? The irony isn't lost on you, and that's what makes you brilliant. You're a walking paradox with regenerating limbs.",
      "Standing still for hours isn't laziness. It's performance art that predators can't appreciate. Your patience isn't just a virtue; it's a survival strategy that's outlasted empires.",
      "Some scream 'look at me!' You whisper 'find me if you can.' That's not hiding, that's being the ultimate puzzle in nature's escape room.",
      "Feeling like furniture? Darling, you're not a stick, you're a scepter in disguise. Every twig wishes it had your presence. Own that botanical dignity.",
      "Your camouflage is so good, scientists keep discovering 'new' species that were there all along? You're not invisible, you're exclusive. VIP viewing only.",
      "That rocking motion isn't nervous energy. It's you conducting the wind symphony. You don't just blend with nature; you dance with it. Slowly. Deliberately. Perfectly.",
      "Herbivore disguised as herbs? That's not ironic, that's being so confident in your lifestyle that you literally embody it. You are what you eat, taken to artistic extremes.",
      "They say you're overlooked, but you're really overseeing. From your perfect twig position, you watch the world rush by. You're not missing out, you're taking notes.",
      "Sometimes the loudest statement is perfect stillness. You're not passive, you're a meditation master teaching the world that power doesn't always need to move to be felt.",
      "Exotic-looking when finally noticed? That's because excellence can only hide for so long. You're not part of the scenery, you're the plot twist everyone missed until the perfect moment."
    ]
  },
  "grylloblattodea": {
    commonName: "Ice Crawlers & Rock Crawlers",
vibe: "Thriving in tough conditions while others complain and retreat. Like you're built for hardship that would break most people. Finding your element in places others consider harsh or unwelcoming.",
    quotes: [
      "Room temperature kills you? That's not fragile, darling. That's having standards so specific, you've turned 'picky' into a survival strategy. You're not cold-blooded; you're cold-perfected.",
      "Living fossil still crawling around glaciers after millions of years? You're not outdated. You're vintage. Classic! The limited edition that never went out of style because ice ages keep coming back.",
      "Years to mature in a nocturnal ice cave? You're not slow. You're fermented to perfection in nature's wine cellar. Good things come to those who wait... especially in subzero temperatures.",
      "They need heated homes; you need a deep freeze. That's not limitation. That's having a mortgage on prime glacial real estate while everyone else fights over beachfront property.",
      "Wingless by choice since before wings were trendy? Why fly south for winter when you ARE winter's favorite child? You don't migrate; you marinate in magnificence.",
      "Finding sustenance in places where nothing else can survive? You're not scavenging. You're the glacier's cleanup crew with a several-year contract and excellent cold-weather benefits.",
      "Your idea of a heat wave is everyone else's hypothermia? That's not weird. That's being calibrated to a different scale of existence. You're living in Celsius while they're stuck in Fahrenheit feelings.",
      "Rock crawler in the scree, ice crawler on the glacier. You're not indecisive; you're bilingual in brutal terrains. Most creatures can't handle one extreme, but you collect them.",
      "Others hibernate through winter; you're out there living your best life in the frost. That's not madness. That's having the whole frozen playground to yourself. No lines, no waiting.",
      "Survived multiple ice ages while other species went extinct? You're not stubborn. You're the subscription service that never gets cancelled. Reliability in six frozen legs.",
      "Your metabolism runs so slow you're basically geological? Perfect! While everyone else rushes, you're playing the long game. Decades-long. Winner takes the next ice age.",
      "Seeking solitude in places that would kill most life instantly? That's not antisocial. That's having standards for your social circle: must survive below freezing.",
      "They say you're from an older, colder time like it's a bad thing. Meanwhile, you're thriving while they're buying heated blankets. Who's evolved now?",
      "Your perfect temperature is everyone else's 'call in sick' weather? Brilliant! You've eliminated all competition by simply existing where they can't. That's not harsh; that's strategic.",
      "Finding beauty in desolate, frozen wastelands? You're not delusional. You're seeing the world without the clutter of fair-weather tourists. Every glacier is your private gallery, every ice cave your personal spa."
    ]
  },
  "mantophasmatodea": {
    commonName: "Gladiators & Heelwalkers & Mantophasmids",
vibe: "Like you're an oddball whose unique traits don't fit anywhere. Your distinctive way of doing things seems weird to everyone else. Still figuring out how to balance all your contradictory qualities.",
    quotes: [
      "Discovered in 2002? Honey, you're not late. You're limited edition. While others have been catalogued to death, you stayed mysterious until the world was ready for your fabulousness.",
      "Walking on your heels like you're wearing invisible stilettos through the Namibian desert? That's not awkward. That's runway ready! Project Runway: Arid Grassland Edition.",
      "Part mantis attitude, part stick insect physique, all gladiator swagger? You're not confused. You're a remix. The greatest hits of predatory excellence in one wingless wonder package.",
      "They named you 'gladiator' because 'fierce tiptoe assassin of the shrublands' was too long for the textbooks. Own that arena, you heel-walking warrior.",
      "Spent millions of years undetected by science? That's not hiding. That's having the longest soft launch in history. Your debut was worth the wait.",
      "Your whole order is younger than YouTube? Perfect! You're not playing catch-up. You're starting fresh without any evolutionary baggage. Version 1.0 and already fierce.",
      "Specialized hunter in a very specific habitat? You're not limited. You're exclusive. A boutique professional with a carefully curated target market. Michelin-starred precision.",
      "That heel-walking gait isn't a quirk. It's a signature! While others stomp, you sashay. Every hunt is a dance, every step a statement. Work it, gladiator.",
      "Living in arid lands where others can't thrive? You're not struggling. You're VIP in nature's most exclusive neighborhood. Desert penthouse with a view to die for. Literally.",
      "Neither full mantis nor full stick, but something entirely new? That's not identity crisis. That's innovation! You're the fusion cuisine of the natural world, and everyone wants a taste.",
      "They studied life for centuries and missed you entirely? That's because excellence can't be rushed. You waited for HD cameras and DNA sequencing to properly capture your essence.",
      "Wingless in a world obsessed with flight? Who needs wings when you've got that heel-walk swagger? You're not grounded. You're making the ground your personal catwalk.",
      "Being a 'new' order doesn't mean you're inexperienced. You've been perfecting your craft since before humans knew you existed. That's not amateur; that's underground legend gone mainstream.",
      "Your scientific name literally means 'mantis-ghost'? Spectacular! You're not just any creature. You're a phantom with better footwork than Fred Astaire.",
      "Balancing different aspects of your nature? Darling, you're not torn between identities. You're proof that the best things come from unexpected combinations. Mantis meets stick meets runway model meets tiny gladiator. That's not confusion; that's complexity."
    ]
  },
  "mantodea": {
    commonName: "Mantids & Praying Mantises",
vibe: "Waiting endlessly for the perfect moment that may never come. Holding back your intensity when you should probably unleash it. Like you're all focus and potential energy with nowhere to strike.",
    quotes: [
      "That praying posture? You're not asking for permission. You're giving the universe a heads-up that something spectacular is about to happen. Hands clasped in deadly meditation.",
      "Head swiveling 180 degrees while your body stays perfectly still? That's not paranoia, love. That's panoramic awareness with a side of 'I see you before you see me.' CEO energy.",
      "Sitting motionless for hours waiting for the perfect moment? You're not procrastinating. You're a sniper with six legs and the patience of a saint. A very hungry saint.",
      "Those raptorial forelegs aren't weapons. They're precision instruments! You're not violent; you're a surgeon who specializes in extremely fast, extremely final procedures.",
      "Masters say 'be like water.' You said 'be like a leaf until it's time to be lightning.' That's not indecision. That's having a broader range than any guru ever dreamed of.",
      "Sexual cannibalism? Listen, some relationships end with 'it's not you, it's me.' Yours end with 'it's not you, it's dinner.' At least you're honest about your appetite for love.",
      "Blending perfectly with flowers while being a ruthless hunter? You're not deceptive. You're a walking metaphor for how beauty and danger dance together. Poetic and practical.",
      "That stillness isn't empty. It's loaded! Like a drawn bow, a held breath, a pause before the punchline. You're not waiting; you're charging up for something magnificent.",
      "Watching you hunt is like watching meditation turn into martial arts in 0.03 seconds. You're not just focused. You're focus incarnate with an appetite.",
      "They see prayer; you see tactical positioning. They see stillness; you see strategy. They see hesitation; you see the space between heartbeats where victory lives.",
      "Your camouflage is so good, flowers get jealous. You're not hiding. You're demonstrating that the best hunters are indistinguishable from paradise until they strike.",
      "Excellent vision, lightning reflexes, infinite patience. You're basically a ninja that learned to meditate from monks and then ate them. Spiritually, of course.",
      "That moment when you finally strike, after hours of waiting? That's not delayed gratification. That's compound interest on your investment in stillness. The returns are spectacular.",
      "Some hunt by chasing, you hunt by becoming the inevitability your prey walks into. That's not passive. That's being so confident you let dinner come to you.",
      "Your whole existence is a masterclass in 'speak softly and carry big spiky forelegs.' Teddy Roosevelt would be proud, if he wasn't worried about becoming lunch."
    ]
  },
  "blattodea": {
    commonName: "Cockroaches & Termites",
vibe: "Surviving everything but getting no credit, only judgment. Unfairly labeled despite your incredible resilience and adaptability. Thriving in tough situations while carrying an undeserved bad reputation.",
    quotes: [
      "Survived every mass extinction, outlived the dinosaurs, and still getting side-eye at parties? That's not being a pest, darling. That's being too successful for the comfort of lesser mortals.",
      "Racing through kitchen shadows? You're not fleeing. You're doing parkour through a world that wasn't ready for your 320-million-year winning streak. Haters gonna hate, survivors gonna survive!",
      "Termite colonies more complex than most corporations? You're not destructive. You're running a multigenerational wood-recycling empire with better communication than most tech startups.",
      "They say you'd survive nuclear war like it's a bad thing. Meanwhile, you're over here treating radiation like a light tan. That's not creepy; that's having a superior warranty on existence.",
      "Living on crumbs and vibes for months? That's not desperation. That's efficiency! You've mastered the art of doing more with less while others panic over missing one meal.",
      "Your gut microbes help you digest wood? Congratulations, you solved renewable energy before humans invented the wheel. That's not primitive; that's partnership goals.",
      "Flattened body for ultimate hide-and-seek mastery? You're not skulking. You're utilizing three-dimensional space like a ninja who studied architecture. Every crevice is a castle.",
      "Building air-conditioned mounds without electricity? Termites, you're not pests. You're sustainable architects whose blueprints humans are still trying to copy. Invoice them for the consultation.",
      "They spray, you adapt. They poison, you evolve. They hate, you proliferate. That's not stubborn; that's being the ultimate 'yes, and...' in the improv show of evolution.",
      "Secret underground termite cities nobody sees? You're not hiding. You're running Atlantis while everyone's looking for you in the wrong dimension. Mysterious and municipal.",
      "Can sense earthquakes, survive floods, navigate by stars you can barely see? You're not a pest. You're a Swiss Army knife with antennae. Prepared for everything, surprised by nothing.",
      "Your bad reputation is just jealousy disguised as disgust. Not everyone can claim their family tree is older than actual trees. You're not unwanted; you're intimidatingly eternal.",
      "Mothers care for their babies, termite queens live for decades, but sure, let's focus on the kitchen thing. You're not gross. You're dedicated parents with questionable PR.",
      "They call exterminators for you like you're the problem, meanwhile you're recycling their waste and aerating their soil. You're not invasive. You're doing unpaid environmental consulting.",
      "Three hundred million years of success and still humble enough to eat leftovers? That's not desperation. That's knowing your worth isn't determined by your menu. You're timeless, resourceful, and absolutely unstoppable."
    ]
  },
  "psocodea": {
    commonName: "Booklice & Barklice & Parasitic Lice",
vibe: "Obsessing over tiny details while missing the bigger picture. Feeling too dependent on others or clinging to old things. Like you're living off scraps in a world that's moving beyond you.",
    quotes: [
      "Nibbling on book paste in a forgotten library corner? You're not a pest. You're a literary critic who takes 'devouring books' literally. Every page turn is your Michelin-star meal.",
      "Committed to one host for life? That's not codependency, darling. That's brand loyalty that would make Apple jealous. You've found your ecosystem and you're committed.",
      "Worried about digital books replacing your dusty paradise? Please! Someone needs to preserve the footnotes of history, and PDF files don't taste nearly as good as aged binding glue.",
      "Living off natural secretions? You're not a freeloader. You're a mobile spa technician providing complimentary exfoliation services. Invoice pending.",
      "Booklice in the humidity, feeding on microscopic fungi? You're not dwelling in decay. You're the sommelier of the decomposition world, finding fine dining where others see dust.",
      "Your entire world is three millimeters of bark or a single feather shaft? That's not limited. That's knowing your neighborhood so well you could give tours. Micro-local living at its finest.",
      "They call you names like it's an insult, but you've achieved what every startup dreams of: perfect product-market fit. Your host doesn't know they need you, but you know they're perfect.",
      "Wingless and wonderful, you prove that not all journeys require flight. Sometimes the best adventure is exploring every microscopic crevice of exactly where you are.",
      "Feeding on organic detritus in old books? You're not destroying knowledge. You're literally digesting history, becoming one with forgotten stories. Very meta, very mindful.",
      "Host-specific to the point of co-evolution? That's not clingy. That's the ultimate long-term relationship! You're not just finding a partner; you're finding a species to grow old with.",
      "Creating silk tunnels on tree bark? You're not infesting. You're adding infrastructure to nature's highways. A tiny civil engineer with excellent taste in real estate.",
      "Your meticulous attention to the overlooked means you find treasures in what others call trash. That's not bottom-feeding. That's archaeological expertise on the microscopic level.",
      "Worried AI will replace old books? Honey, you survived the printing press, the internet, and e-readers. You're the constant in a world of variables. Dust always accumulates, and you'll always be there for it.",
      "Each of you is a specialist in your field. That's not parasitism. That's having a PhD in exactly one thing and being brilliant at it.",
      "Living among ancient texts or ancient feathers, you're proof that the old ways still matter. You're not obsolete. You're vintage, essential, and quietly keeping the world's forgotten corners alive."
    ]
  },
  "thysanoptera": {
    commonName: "Thrips",
vibe: "Feeling small and insignificant despite making a real impact. Like you're annoying or bothering people just by being yourself. Having unconventional methods that work but aren't appreciated.",
    quotes: [
      "Asymmetrical mouthparts? You're not broken, love. You're proof that perfection is overrated. While others waste energy on symmetry, you're getting the job done with half the equipment and twice the style.",
      "Those fringed wings aren't just decorative. They're fashion meeting function at the microscopic level! You're not tiny; you're traveling in haute couture that physics majors write dissertations about.",
      "One millimeter long and making farmers nervous worldwide? That's not insignificant. That's having a presence so powerful it's measured in agricultural impact reports. Small package, seismic influence.",
      "Feeling invisible until someone's suddenly itching? You're not annoying. You're a reminder that the smallest touches can leave the biggest impressions. Very zen, if zen occasionally bit people.",
      "Your left mandible does all the work while the right takes permanent vacation? That's not imbalanced. That's efficiency! You've streamlined success before minimalism was trendy.",
      "Transmitting plant viruses like tiny mail carriers of change? You're not destructive. You're accidentally revolutionary. Sometimes the biggest changes come from the smallest messengers.",
      "Flying on fringed wings that look like feather dusters? Darling, you're not struggling. You're proving that aerodynamics textbooks missed a chapter. The 'thrips exception,' they'll call it.",
      "Millions of you descending on a field? That's not an infestation. That's a masterclass in collective bargaining. No single raindrop believes it's responsible for the flood, but here you are, making waves.",
      "So small that most people don't know you exist until their plants start looking suspicious? You're not sneaky. You're operating on a need-to-know basis, and most don't need to know until it's too late.",
      "Hunting even tinier prey? You're not just small. You're relatively mighty! It's not about your size; it's about who's smaller. Perspective is everything.",
      "Those fringe wings work like tiny paddles in the air? You're not flying. You're swimming through sky soup. Different technique, same destination. Innovation looks different at every scale.",
      "Causing agricultural impact while being barely visible? That's not pest behavior. That's being an economic force multiplied by millions. You're basically a tiny stock market crash with wings.",
      "Your unconventional mouthparts make you unique, not broken. While others follow blueprints, you're out here proving that doing things differently can still get results. Left-handed excellence!",
      "One of you is a whisper, a million of you is a roar. You're not insignificant. You're part of a symphony where every tiny note matters. The crescendo is coming, and you're in it.",
      "Feeling overlooked until suddenly everyone's paying attention? That's the thrips way. Invisible until critical mass, ignorable until undeniable. You're not just present; you're eventually omnipresent."
    ]
  },
  "hemiptera": {
    commonName: "True Bugs",
vibe: "Misunderstood because your true nature doesn't fit neat categories. Having a sharp, direct approach that rubs people the wrong way. Incredibly adaptable but never quite fitting in anywhere perfectly.",
    quotes: [
      "That rostrum isn't just a mouthpart. It's a precision instrument for extracting exactly what you need from life. Some use hammers, you use a surgical straw. That's not weird; that's refined.",
      "Seventeen years underground before your big cicada debut? That's not procrastination, darling. That's the longest drum roll in history before the most spectacular solo. Worth the wait!",
      "Water strider skating across liquid like it's solid ground? You're not defying physics. You're rewriting it with surface tension and attitude. Jesus walked on water; you make it look easy.",
      "Aphids cloning themselves for efficiency? That's not lonely. That's building an empire without the drama of dating. Parthenogenesis: when you're too busy succeeding to swipe right.",
      "Stink bug with a memorable defense mechanism? You're not offensive. You're unforgettable! Some creatures are forgotten instantly; you leave a lasting impression. Own that olfactory autograph!",
      "Your wings form an 'X' on your back when resting? That's not random. That's nature marking the spot where authenticity lives. 'X' marks the true bug.",
      "Scale insects so still they look like part of the plant? You're not boring. You're committed to the bit. Method acting at its finest, plus you get free meals.",
      "From bed bugs to assassin bugs, you've got family in every neighborhood. That's not invasive. That's successful diversification! Your portfolio would make Wall Street weep.",
      "That piercing mouthpart makes some nervous? Good. Not everyone deserves access to your depths. You're not aggressive; you're selective about where you invest your point.",
      "Spittlebug hiding in your own foam castle? That's not gross. That's building your own spa wherever you go. Mobile self-care with architectural flair.",
      "Producing honeydew that ants literally farm you for? You're not being used. You're in a profitable partnership. Your waste is someone else's treasure. That's circular economy goals.",
      "Loud as a cicada or quiet as a scale insect, either way, you're living your truth. Volume doesn't determine value; authenticity does. Sing your song or whisper your wisdom.",
      "Your mouthparts are literally built different? Perfect! While others chew through problems, you get straight to the point. That's not limitation; that's laser focus in biological form.",
      "Incomplete metamorphosis means you're recognizable from day one? You're not unfinished. You're consistently yourself through every life stage. No cocoon needed when you're already iconic.",
      "They call you 'True Bugs' because even science recognizes your authenticity. You're not pretending to be anything else. You're pointedly, proudly, persistently yourself. That's true success."
    ]
  },
  "neuroptera": {
    commonName: "Lacewings & Antlions & Mantidflies & Owlflies",
vibe: "Looking gentle and delicate when you're actually fierce inside. Cleaning up messes and solving problems without getting recognition. Like your helpful nature gets overlooked because you're not flashy.",
    quotes: [
      "Lace wings that could grace a fairy's wardrobe, but larvae that would make horror movie directors jealous? That's not deception, love. That's having range. Delicate couture by day, aphid apocalypse by night.",
      "Your babies are called 'aphid lions' and they live up to the name? While you're sipping nectar looking ethereal, your kids are out there running a pest control empire. That's not bad parenting; that's delegation.",
      "Antlion larvae sitting at the bottom of death pits they engineered themselves? That's not lazy. That's working smarter, not harder! Why chase dinner when physics can deliver it?",
      "Mantidfly with a lacewing's grace and a mantis's murder mittens? You're not confused. You're a greatest hits album of predatory evolution. Best of both worlds, with wings.",
      "Those intricate wing veins aren't just pretty. They're engineering poetry that would make architects weep. You're not delicate; you're structurally magnificent with a license to kill.",
      "Doodlebug larvae drawing deadly spirals in the sand? That's not doodling. That's death-trap artistry! Your kids turned geometry into gastronomy.",
      "Adults pollinating flowers while larvae demolish pest populations? You're not two-faced. You're playing the long game. Save the plants coming and going. Ecological genius.",
      "Your larvae decorate themselves with their victims' empty husks? That's not macabre. That's upcycling with attitude. Camouflage meets trophy case meets sustainable fashion.",
      "Looking like a damselfly until someone notices those clubbed antennae? You're not an imposter. You're keeping people guessing. Mystery is your middle name, excellence is your game.",
      "Larvae infiltrating spider egg sacs? That's not rude. That's finding free room and board in the most unlikely places. Airbnb for the audacious.",
      "Green lacewing singing love songs with your abdomen? You're not just beautiful and deadly. You're musical too! Triple threat with translucent wings.",
      "Your transformation from terrifying larva to delicate adult isn't false advertising. It's character development. Every good story needs a plot twist, and yours has mandibles.",
      "'Beneficial insect' sounds so clinical. You're not just beneficial. You're a necessity dressed in gossamer, a garden's guardian angel with a seriously compelling origin story.",
      "Those antlion pits aren't just traps. They're patience made visible. Your larvae literally dig their own success, one grain of sand at a time. That's not predation; that's meditation with meals.",
      "Wearing beauty like armor while your children wage war on aphids? That's not contradiction. That's having your cake and eating pests too. You've mastered the art of being simultaneously heaven-sent and hell-bent."
    ]
  },
  "megaloptera": {
    commonName: "Dobsonflies & Alderflies & Hellgrammites",
vibe: "Your intimidating appearance scares people away before they know you. Going through dramatic changes that feel monstrous and overwhelming. Having impressive abilities that feel ceremonial rather than useful.",
    quotes: [
      "Hellgrammite larva looking like a tiny river dragon? That's not terrifying. That's being the bouncer at nature's most exclusive club: Clean Water Only. Your face says 'members only' and the members are grateful.",
      "Those male dobsonfly mandibles longer than your entire body? Darling, you're not overcompensating. You're carrying ceremonial swords to a dance-off. All show, all love, no actual stabbing required.",
      "Spending years as an armored underwater predator just to become a gentle giant looking for romance? That's not inconsistent. That's the ultimate glow-up story! From horror to heart-eyes.",
      "Your presence means the water's pristine? You're not just scary-looking. You're a five-star Yelp review for river quality. 'Would spawn here again,' says every clean-water enthusiast.",
      "Female dobsonflies with practical mandibles while males sport the tusks? You're not missing out. You can actually eat while they're trying to figure out how to navigate doorways. Function over fashion, love.",
      "Three years terrorizing stream bottoms as a hellgrammite, three weeks finding love as an adult? That's not unfair. That's front-loading your career so you can focus on what matters: waterside romance.",
      "Looking so fierce that fishermen use you as bait? That's not unfortunate. That's being so authentically powerful that even predators recognize your energy. Intimidation as currency.",
      "Those lateral filaments making you look extra monstrous? They're not for show. They're breathing apparatus! You're not a monster; you're a snorkel with attitude.",
      "Adult alderflies living quietly by streams after their hellgrammite phase? You're not boring. You're retired from the underwater thunderdome. You've earned your peaceful waterfront property.",
      "Can't survive in polluted water because you have standards? That's not weakness. That's being the environmental canary with mandibles. Your absence is a warning; your presence is a blessing.",
      "Those tusks that can't even grab prey properly? Perfect! You're proof that sometimes the biggest weapons are just conversation pieces. 'Nice mandibles.' 'Thanks, they're just for show.'",
      "From stream-bottom nightmare to flying love-seeker in one metamorphosis? You're not having an identity crisis. You're showing the world that everyone deserves a second act.",
      "Adults barely eating because you're too focused on finding love? That's not dysfunction. That's priorities! Who needs dinner when you've got three weeks to create the next generation?",
      "Your larvae are so impressive that bass use them as their favorite snack? You're not prey. You're premium. Even fish recognize quality when they taste it.",
      "Looking like an alien face-hugger as a baby but growing up to be a peaceful stream-dweller? That's not false advertising. That's character development. Your origin story is just more dramatic than most."
    ]
  },
  "raphidioptera": {
    commonName: "Snakeflies",
vibe: "Feeling old-fashioned or outdated in a fast-moving world. Waiting patiently for your moment while everyone else rushes ahead. Like your unique perspective isn't valued in current times.",
    quotes: [
      "That swan-neck flexibility isn't a deformity. It's a periscope for opportunity. While others crane awkwardly, you smoothly survey every angle like a tiny, predatory yoga master.",
      "Ancient lineage making you feel outdated? Please. You're not old-fashioned, you're vintage verified. Your design has been field-tested for millions of years while others are still in beta.",
      "Elongated prothorax giving you that snake-strike silhouette? You're not creepy. You're ergonomically optimized for precision. Form followed function before it became a design principle.",
      "Patient hunter waiting in the foliage? That's not procrastination. That's having the discipline to know the difference between 'a' moment and 'THE' moment. Timing is everything, and yours is impeccable.",
      "Your head moves independently while your body stays still? Congratulations, you've mastered the art of looking busy while actually being strategic. Corporate America could learn from you.",
      "Female with that impressive ovipositor? You're not just laying eggs. You're precision-placing the future in exactly the right spot. That's not reproduction; that's strategic deployment.",
      "Primitive holometabolous insect? You're not behind the times. You're the original proof of concept that transformation works. Everyone else is just following your ancient blueprint.",
      "That neck isn't just long. It's your competitive advantage. While others commit their whole body to look somewhere, you just swivel and assess. Efficiency in motion.",
      "Living in leaf litter as larvae, hunting from shrubs as adults? You're not indecisive. You're vertically integrated. Ground floor to penthouse, you know every level of the game.",
      "Strike like a snake but with wings? You're not having an identity crisis. You're a chimera of effectiveness. Best of both worlds, plus you can fly away from your mistakes.",
      "Your unique perspective isn't weird. It's panoramic. While others see obstacles, your flexible viewpoint finds opportunities they literally cannot turn their heads to notice.",
      "Ancient design still catching modern prey? That's not outdated. That's timeless excellence. If it ain't broke, don't evolve it. You're the little black dress of predatory design.",
      "That distinctive neck makes you unmistakable? Good. In a world of conformist body plans, you're immediately recognizable. You're not odd; you're branded.",
      "Waiting motionless until the perfect moment appears? You're not inactive. You're a loaded spring with eyes. Potential energy with a swivel mount. Physics professors should study you.",
      "They say you look old-fashioned, but you're out here with built-in image stabilization and 180-degree rotation. You're not primitive. You're so advanced it took millions of years for cameras to catch up."
    ]
  },
  "coleoptera": {
    commonName: "Beetles",
vibe: "Stuck in a protective shell that's becoming more prison than armor. Feeling clumsy and earthbound when you know you could soar. Hidden capabilities that no one expects because of your tough exterior.",
    quotes: [
      "That shell feeling heavy? Darling, you're not wearing armor—you're wearing possibility with a security system. Every beetle knows: the best surprises come in hard-shelled packages.",
      "One in every four animals on Earth is a beetle. You're not 'just another bug'—you're part of the most successful franchise in evolutionary history. McDonald's wishes it had your market penetration.",
      "Firefly flashing your light in the darkness? That's not showing off—that's being a beacon of hope with a built-in disco ball. Some beetles eat dung; you literally glow about it.",
      "Those elytra aren't locking you in—they're keeping the world out until you're ready to unfurl. You're not trapped; you're in a chrysalis with better security features.",
      "Scarab beetle rolling dung into perfect spheres? You're not dealing with crap—you're turning life's messiest moments into geometrically perfect opportunities. That's alchemy, love.",
      "Weevil with that distinctive snout? You're not nosy—you're precisely equipped for getting to the heart of matters others can't even reach. Specialized is not the same as strange.",
      "Feeling clumsy with those hard wing covers? That's like complaining your Mercedes has too much armor. You're not awkward—you're driving a tank that transforms into a jet.",
      "Ladybug, beloved by gardeners everywhere? You're not cute—you're a recognized hero in polka dots. Even your PR is naturally perfect. Aphids fear you; humans adore you.",
      "Grub stage feeling unglamorous? Every stag beetle started where you are. You're not stuck in the dirt—you're gathering strength for your horned glory days. Patience, little tank.",
      "Complete metamorphosis means you get multiple chances to reinvent yourself. That's not identity crisis—that's having a life plan with built-in plot twists. Egg, grub, pupa, magnificent beetle. Every stage intentional.",
      "Four hundred thousand species and counting? You're not lost in the crowd—you're proof that success comes in endless variations. There's a beetle way for every way of being.",
      "Your chewing mouthparts can tackle anything? While others sip and pierce, you take life in satisfying, decisive bites. That's not primitive—that's knowing how to properly savor existence.",
      "Those hidden wings under your shell? You're not deceiving anyone—you're the ultimate 'more than meets the eye' story. Clark Kent had glasses; you have elytra.",
      "Dung beetle navigating by the Milky Way? You're not just pushing poop—you're using celestial navigation to move forward. That's finding your North Star in the messiest situations.",
      "Strongest insect relative to size, most diverse order on the planet, found literally everywhere? You're not just surviving—you're the definition of thriving. Your shell isn't armor; it's a crown worn by Earth's most successful dynasty."
    ]
  },
  "strepsiptera": {
    commonName: "Twisted-wing Parasites & Strepsipterans",
vibe: "Living such a unique lifestyle that no one understands or relates. So deeply connected to others that you're losing your own identity. Influencing from within while feeling invisible and unacknowledged.",
    quotes: [
      "Male strepsipteran with raspberry eyes and fan wings living for one glorious day? You're not tragic. You're concentrated purpose. Some take decades to find their mission; you were born knowing it.",
      "Female spending your entire life intimately connected to another being? That's not codependency, darling. That's achieving a level of integration that therapists only dream about. You don't just influence; you transform from within.",
      "Your lifestyle makes everyone uncomfortable? Good. Comfort never changed anything. You're living proof that the most profound impacts often come from the most unconventional connections.",
      "Males flying free while females embed deep? You're not unequal. You're specialized. Some changes happen in the spotlight; yours happen in the profound privacy of true transformation.",
      "Causing 'stylopization' in your host? You're not a parasite. You're a living revolution, changing the system from inside. Every activist wishes they had your level of systemic impact.",
      "Lost your eyes, legs, and wings to become pure purpose? That's not sacrifice. That's evolution's way of saying 'you've transcended the need for accessories.' Minimalism at its most extreme.",
      "Your larvae actively hunt for the perfect host? You're not desperate. You're selective. Even at the cellular level, you know that not every connection is worth the transformation.",
      "Those raspberry eyes see the world in ways others can't imagine? Perfect. Your brief flight isn't about longevity. It's about seeing everything differently in the time you have.",
      "Living inside another creature, fundamentally altering their existence? You're not invasive. You're intimacy incarnate. Some relationships change you; yours change everything.",
      "Your life cycle is too weird for most textbooks? That's not a bug. That's a feature. You're proof that nature's imagination exceeds human comprehension. Stay incomprehensible, you magnificent oddity.",
      "Males with haltere-like forewings? You've literally flipped the script on flight. While others follow conventional wisdom, you're out here proving that there's always another way to soar.",
      "Becoming one with your host so completely you share their fate? That's not losing yourself. That's the ultimate commitment. 'Till death do us part' has nothing on your level of dedication.",
      "Your influence is invisible but profound? You're not hidden. You're embedded. Like the best ideas, you work from within until the change is so complete, no one remembers the before.",
      "Extreme sexual dimorphism making you unrecognizable as the same species? You're not confused. You're proof that sometimes the same goal requires radically different approaches. Diversity in unity.",
      "Your entire existence challenges what people think is possible? Brilliant. You're not an alien. You're an earth-native reminder that reality is stranger and more wonderful than our wildest dreams. Keep bending minds, you twisted-wing wonder."
    ]
  },
  "hymenoptera": {
    commonName: "Bees & Wasps & Ants",
vibe: "Overwhelmed by endless work and social obligations buzzing around you. Feeling defensive and protective but coming across as aggressive. Burnt out from creating sweetness while having to sting when threatened.",
    quotes: [
      "Waggle dancing your stress to the colony? That's not complaining, love. That's turning your overwhelm into GPS coordinates for success. Even your panic has choreography and purpose.",
      "Solitary bee building alone while honeybees build together? Both valid. You don't need a corporation to be CEO of your own flower empire. Some revolutions need armies; some just need you.",
      "That stinger isn't aggression. It's punctuation. You're not mean; you're fluent in both honey and exclamation points. Sometimes life needs sweetness, sometimes it needs a sharp point well made.",
      "Ant carrying 50 times your body weight up a vertical wall? That's not showing off. That's Tuesday. Your 'impossible' is everyone else's 'laws of physics.' Casual excellence is still excellence.",
      "Paper wasp architect building without blueprints? You're not just crafting. You're proving that sometimes the best communities are built one chewed-up fiber at a time. Sustainable construction since forever.",
      "Division of labor making you feel pigeonholed? Remember: the queen started as a worker too. Your current role isn't your ceiling. It's your launching pad. Every empire needs its foundation.",
      "Parasitic wasp laying eggs in other insects? That's not cruel. That's outsourcing childcare to the competition. Your kids literally grow stronger by conquering obstacles. Hardcore parenting.",
      "Feeling defensive of your hive? Good. That's not paranoia. That's knowing what's worth protecting. Your willingness to sting for what you love is what makes the honey worth making.",
      "Bumblebee breaking physics with every flight? They said you couldn't fly, yet here you are, turning flowers into futures. Your very existence is a middle finger to impossibility.",
      "Working yourself to exhaustion for the colony? Remember: even worker bees take time to dance. Your productivity includes joy, communication, and the occasional flower-nap. Balance, darling.",
      "Your pheromones coordinate thousands without a single meeting? You're not a cog in the machine. You're wireless communication perfected. Your stress literally helps others navigate. That's leadership.",
      "Honeybee or hornet, your sting costs you everything? That's not weakness. That's knowing some things are worth your whole life. Most never find something that precious. You have.",
      "Ant queen living for decades while workers live for weeks? That's not unfair. That's specialization. Some are built for sprints, some for marathons. Both are running toward the same tomorrow.",
      "Creating royal jelly to make ordinary larvae into queens? You're not just feeding babies. You're literally manufacturing majesty. Your grocery list includes 'essence of sovereignty.' Casual magic.",
      "Feel like just another worker in an endless colony? Honey, you're not replaceable. You're essential. The hive doesn't work without each bee, the hill doesn't rise without each ant. Your small part is someone else's everything."
    ]
  },
  "trichoptera": {
    commonName: "Caddisflies & Sedge-flies & Rail-flies",
vibe: "Building protective barriers from whatever scraps life gives you. Feeling like you have to construct your own safety from nothing. Resourceful but tired of always having to make do with less.",
    quotes: [
      "Gluing pebbles to your silk house like an underwater Gaudí? That's not obsessive. That's having standards. Your mobile home isn't just protection; it's a rolling portfolio of your exquisite taste.",
      "Each caddisfly species has its own architectural style? You're not following trends. You're genetically programmed for bespoke design. Your DNA is literally an interior decorating degree.",
      "Can't survive in polluted water? That's not being delicate, darling. That's having the self-respect to demand a quality environment. Your presence literally says 'this place is worth living in.'",
      "Spending months as an aquatic jeweler just to become a fuzzy moth-thing that doesn't even eat? That's not anticlimax. That's knowing when to shift from creating to procreating. Different life stages, different priorities.",
      "Your larvae case travels with you wherever you go? You're not dragging baggage. You're pioneering sustainable, portable living. Tiny houses wish they had your efficiency.",
      "Collecting specific materials for your case like a picky shopper? That's not fussy. That's curation. While others grab whatever, you're building a home that's also a self-portrait.",
      "Those hairy wings aren't glamorous? Who cares when you spent your youth as an underwater Fabergé? You've already made your artistic statement; now you're just here to dance and make babies.",
      "Using snail shells in your case construction? That's not morbid. That's upcycling with panache. One creature's abandoned home becomes your architectural flourish. Circle of life, with style.",
      "Your silk glands work underwater? While others need dry conditions, you're weaving masterpieces in the current. That's not just skill. That's defying physics with every thread.",
      "Fixed retreat or portable case? Either way, you're proving home isn't a place. It's what you build with your own two silk glands and impeccable taste in debris.",
      "Adult caddisflies living just long enough to mate? You're not rushed. You're focused. Some spend decades avoiding commitment; you turned your entire adult life into one beautiful 'yes.'",
      "Each larva's case is unique as a fingerprint? You're not just building shelter. You're signing your work. Every twig placement says 'an artist lived here.'",
      "Sensitive to pollution means you're weak? No, love. It means you're calibrated to excellence. You're not failing to adapt; you're maintaining standards in a world that's lowering theirs.",
      "Transform from jewel-encrusted architect to fuzzy flying romantic? That's not identity crisis. That's range. Beyoncé has less dramatic costume changes than you.",
      "Your carefully constructed case looks like random junk to others? Their loss. You see treasure where they see trash, build homes where they see hopelessness. That's not delusion. That's vision, one grain of sand at a time."
    ]
  },
  "mecoptera": {
    commonName: "Scorpionflies & Hangingflies & Snow Scorpionflies",
vibe: "Your unique qualities are constantly misunderstood or judged. Giving thoughtful gifts or gestures that people find weird. Like your perfectly logical approach seems bizarre to everyone else.",
    quotes: [
      "That 'scorpion tail' causing alarm? Honey, it's not a weapon. It's a love letter curled into anatomical poetry. You're not dangerous; you're romantically equipped with hardware others can't even comprehend.",
      "Bringing dead bugs as courtship gifts? That's not creepy. That's practical romance. While others bring flowers that die, you bring protein that provides. You're the meal-prep romantic of the insect world.",
      "Hanging upside down waiting for dinner to fly by? You're not lazy. You're a chandelier with appetite. Some hunt their food; you've turned gravity into your personal delivery service.",
      "Snow scorpionfly thriving on frozen ground when others hibernate? That's not madness. That's having the winter wonderland all to yourself. You're not weird; you're seasonally exclusive.",
      "That elongated face isn't unfortunate. It's specialized equipment. While others make do with regular mouthparts, you're sporting a custom-built rostrum. Bespoke biology, darling.",
      "Your salivary secretions count as romantic gifts? Listen, you're literally giving part of yourself. That's not gross. That's commitment. Some give chocolates; you give essence of you.",
      "Male hangingfly presenting prey to females mid-air? That's not showing off. That's dinner theater at 30 feet. You've combined dating and dining into aerial performance art.",
      "Looking like you escaped from prehistory? You're not outdated. You're vintage verified. Your whole vibe says 'I was quirky before quirky was cool.' Original hipster with wings.",
      "Four wings when everyone thinks you only have two? That's not excessive. That's having backup for your backup. You're the insect equivalent of always carrying a spare everything.",
      "Your mating claspers scare people more than actual stingers? Perfect. You're proof that love is scarier than war, and you're dressed for the occasion. Romantic and terrifying. The best combination.",
      "Active in winter when everyone else is dormant? You're not antisocial. You're avoiding the crowds. Some bugs need summer parties; you prefer winter's intimate conversations on snow.",
      "Hanging by your front legs with your back legs ready to grab? You're not awkward. You're a living bear trap with better manners. Patience and geometry, perfectly combined.",
      "Those nuptial gifts aren't desperate. They're traditional. You were doing dinner-and-a-date before vertebrates existed. Don't let anyone shame your time-tested romantic strategies.",
      "Caterpillar-like larvae living in leaf litter? Even your babies are keeping it low-key and mysterious. The apple doesn't fall far from the peculiar, wonderful tree.",
      "They call you an evolutionary enigma? Good. You're not meant to be easily categorized. You're the bug equivalent of a David Lynch film. Beautiful, strange, and impossible to forget. Keep them guessing, you magnificent oddity."
    ]
  },
  "siphonaptera": {
    commonName: "Fleas",
vibe: "Restless and jumpy, always moving but never quite settling. Your talents feel specialized to the point of being annoying. Making a big impact but in ways that irritate rather than impress.",
    quotes: [
      "Can jump 200 times your body height? That's not hyperactive, darling. That's having springs where others have limitations. You're not jumpy; you're equipped with the world's most efficient personal launch system.",
      "Those backward-pointing spines making you impossible to remove? That's not clingy. That's commitment with hardware. When you decide to stick around, you bring the engineering to back it up.",
      "Laterally compressed to slip through any situation? You're not sneaky. You're streamlined for success. While others get stuck, you're navigating life's tangles like a tiny, determined submarine.",
      "Making everyone itchy just by existing? That's not being a pest. That's having presence. Some bugs are forgettable; you leave an impression that lasts for days. Marketing executives wish they had your retention rates.",
      "No wings but you can reach heights others only dream of? Who needs flight when you've got those thighs? You're proof that there's more than one way to touch the sky.",
      "Your larvae eat your poop? Okay, that sounds bad, but it's actually brilliant recycling. You're running a zero-waste household before it was trendy. Sustainability starts at home, even if home is someone's fur.",
      "Specialized to the point where you can't survive without a host? That's not weakness. That's knowing exactly what you need and refusing to compromise. Generalists are so last epoch.",
      "Disease vector reputation got you down? Listen, you're not responsible for your hitchhikers. You're just trying to get a meal, not start a pandemic. Don't let them blame the messenger.",
      "So small but causing such a big reaction? You're not insignificant. You're concentrated impact. It's not about size; it's about making sure you're absolutely unforgettable.",
      "Your whole life revolves around finding the perfect warm body? That's not desperate. That's focused. While others waste time on small talk, you know exactly what you're looking for: dinner and a mobile home.",
      "Those incredible legs aren't just for jumping away. They're for jumping TO opportunity. You don't flee; you relocate strategically. Every leap is a calculated career move.",
      "Living in someone's bedding sounds creepy until you realize it's basically a heated, food-delivery service apartment. You're not a parasite. You're a savvy real estate opportunist.",
      "Your ancestors survived the extinction of the dinosaurs by switching to mammals? That's not opportunistic. That's adaptive genius. When life closes a door, you jump through a window. Literally.",
      "Feeling unappreciated for your specialization? Remember: Olympic high-jumpers don't apologize for being one-trick ponies. Your trick just happens to be surviving by being impossibly athletic and tenacious.",
      "Making others uncomfortable with your very existence? Good. Comfort breeds complacency. You're a tiny reminder that life includes challenges, and sometimes those challenges have world-class vertical leaps and really know how to hang on."
    ]
  },
  "diptera": {
    commonName: "True Flies",
vibe: "Your energy and presence overwhelm people who prefer quiet. Going through major changes that happen too fast for others to see. Playing vital roles that are completely unappreciated or even reviled.",
    quotes: [
      "Those halteres spinning like tiny gyroscopes while others lumber around with four wings? You're not half-equipped. You're aerodynamically superior. Less wings, more wins. That's efficiency, darling.",
      "Compound eyes seeing the world in thousands of frames per second? You're not overwhelmed. You're operating in high definition while everyone else is stuck buffering. Your reality runs at a better frame rate.",
      "Maggot phase feeling unglamorous? Honey, you're doing the dirty work that keeps the world turning. Without you, we'd be neck-deep in unrecycled everything. You're not gross; you're essential infrastructure.",
      "Your buzz annoying people? That's the sound of someone operating at peak performance. Silence is overrated when you're vibrating at the frequency of getting things done.",
      "Hoverfly mimicking a bee while secretly being a pollination ninja? You're not a faker. You're double-agent fabulous. Let them think what they want while you save their gardens.",
      "Mosquito getting side-eye for your dining choices? Listen, you're not a vampire. You're a working mother who needs protein for her kids. Your meal plan just happens to be more direct than most.",
      "Fruit fly in the genetics lab, unlocking the secrets of heredity? You're not a pest. You're a tiny professor with more Nobel prizes to your species' name than most universities. Respect the research.",
      "Robber fly catching prey mid-flight? That's not aggressive. That's being an aerial ace. While others need webs or ambushes, you're running a flight-intercept program. Top gun with six legs.",
      "Transform from legless larva to winged wonder? That's not a glow-up. That's a complete career pivot. From sanitation engineer to aerial artist. Talk about range.",
      "Those giant eyes make you look alien? Good. You're seeing angles others can't imagine, processing information at speeds that would crash their systems. You're not weird; you're upgraded.",
      "Blow fly larvae in wound therapy, literally healing while everyone cringes? You're not disgusting. You're medical equipment that works better than some prescriptions. Gross? Try groundbreaking.",
      "Your entire life cycle takes days or weeks while others take years? That's not rushed. That's living at the speed of now. You experience more generations of change than others see in a lifetime.",
      "Crane fly pretending to be a giant mosquito? You're not scary. You're a gentle giant cosplaying as your tough cousin. All the intimidation, none of the bloodlust. Strategic styling.",
      "Decomposer, pollinator, genetic model, medical marvel? Your family reunion is more diverse than the UN. You're not just a fly; you're a Swiss Army knife with wings.",
      "Feeling misunderstood because you process garbage into garden gold? Darling, you're not annoying. You're alchemy in action. You literally turn death into life, decay into renewal. If that's not magic, what is? Buzz proudly, you high-frequency hero. The world spins because you do."
    ]
  },
  "protura": {
    commonName: "Coneheads & Proturans",
vibe: "Navigating life without the social tools everyone else seems to have. Feeling directionless or primitive compared to others. Content in your small world but wondering if you're missing something.",
    quotes: [
      "No eyes, no antennae, just vibes and forelegs? You're not sensory-deprived. You're running on the original operating system. Who needs updates when version 1.0 still works perfectly in your soil sanctuary?",
      "Adding segments as you grow instead of being born complete? That's not unfinished. That's getting expansion packs for your body. You're literally leveling up with each molt.",
      "Living your whole life in a few millimeters of soil? You're not limited. You're a specialist in microverse magnificence. Some need the whole world; you've found infinity in a teaspoon of earth.",
      "Conical head with no eyes to see or antennae to wave? Perfect. You're aerodynamic in the soil and uncluttered by unnecessary accessories. Minimalism before it had a name.",
      "Using your legs as feelers? That's not makeshift. That's multitasking at the cellular level. Every step is reconnaissance, every movement a sensory symphony. Dancing and detecting simultaneously.",
      "So primitive they debate if you're even a 'true' insect? Darling, you're not having an identity crisis. You're too original for categories. You predate their need to label everything.",
      "Feeding on mycorrhizal fungi in the dark? You're not just eating. You're communing with the underground network that feeds forests. That's not primitive; that's plugged into nature's internet.",
      "No one knows you exist unless they're looking REALLY hard? That's not invisibility. That's exclusivity. You're not overlooked; you're a secret the soil keeps for the truly curious.",
      "Your whole world fits between soil particles? You're not thinking small. You're proving that empires can exist in spaces others dismiss as gaps. Microscopic majesty is still majesty.",
      "Navigating without eyes in eternal darkness? You're not lost. You're so perfectly calibrated to your environment that sight would be redundant. You don't need to see when you can simply know.",
      "They call you primitive but you're still here, unchanged and thriving? That's not failure to evolve. That's being so perfectly designed from the start that evolution took one look and said 'nailed it.'",
      "Your forelegs pulling double duty as sensors? While others specialized themselves into corners, you kept it simple and flexible. That's not primitive. That's pure genius.",
      "Living on decay and fungi, recycling the forgotten bits? You're not bottom-feeding. You're finding treasures in what others abandon. One hexapod's trash is your mycological feast.",
      "So small scientists missed you for centuries? You're not insignificant. You're proof that the most fundamental things often hide in plain sight. Size isn't impact; presence is.",
      "No fancy features, no showy adaptations, just pure, distilled existence? You're not lacking. You're the haiku of the hexapod world. Why say more when less says everything? You're perfection in 2.5 millimeters, navigating by touch in a world that doesn't even know it needs you. But it does. Oh, it does."
    ]
  },
  "diplura": {
    commonName: "Two-pronged Bristletails & Diplurans",
vibe: "Preferring the quiet underground while everyone else seeks spotlight. Feeling simple and basic in a world that values complexity. Like you're doing essential work that no one notices or values.",
    quotes: [
      "Two prongs at your rear acting like a second set of antennae? That's not weird, darling. That's having eyes in the back of your... well, technically your abdomen. You're seeing life from both ends, literally.",
      "Living your whole life in darkness without needing eyes? You're not blind. You're so perfectly tuned to your world that vision would just be showing off. Touch is your superpower.",
      "Those cerci working as forceps, feelers, or defensive tools? You're not indecisive. You're the Swiss Army knife of the soil. One body part, multiple functions. That's not primitive; that's efficient.",
      "Pale as a ghost and living underground? You're not avoiding the sun. You're avoiding the drama. While surface dwellers deal with weather, predators, and trends, you're steady as bedrock.",
      "Your antennae AND cerci both collecting information? That's not redundancy. That's 360-degree awareness. You're getting the news from both ends while others barely know what's behind them.",
      "Feeding on decay in the quiet darkness? You're not gross. You're the universe's cleanup crew with a corner office in the earth's basement. Someone's got to keep the foundation tidy.",
      "Basal lineage making you feel outdated? Please. You're not old-fashioned. You're time-tested. You've been successfully not-needing-eyes since before eyes were trendy.",
      "Those pincer-like cerci on some species? You're not aggressive. You're prepared. It's like having a built-in multi-tool where others just have a decorative tail. Function over fashion, always.",
      "Content in your underground niche while others seek fame above? That's not settling. That's knowing where you thrive. Not everyone needs spotlights when they've got the whole understory.",
      "Moniliform antennae looking like tiny bead necklaces? Even your sensory equipment has style. You're not plain. You're accessorizing at the molecular level.",
      "Living where it's always moist and dark? You're not hiding. You're in the VIP section of soil society. Exclusive, climate-controlled, and no paparazzi. Perfect.",
      "Your world measured in millimeters of soil? That's not limited. That's focused. While others spread thin across the surface, you know every grain of your kingdom intimately.",
      "Those filamentous cerci waving like underground flags? You're not just feeling around. You're reading the earth's braille, getting messages others don't even know exist.",
      "Simple body plan, no wings, no fancy colors? Perfection doesn't need accessories. You're the little black dress of hexapods. Classic, functional, and absolutely timeless.",
      "Operating in spaces others don't even know are habitable? You're not overlooked. You're discovering frontiers in your own backyard. Every soil particle is your universe, every touch a revelation. You're proof that the most profound journeys happen when you dig deep instead of flying high."
    ]
  },
  "lepidoptera": {
    commonName: "Butterflies & Moths & Skippers",
vibe: "Stuck in the messy, uncertain middle of major life transformation. Feeling fragile and vulnerable during this transitional phase. Like you're dissolving into goo before you can become who you're meant to be.",
    quotes: [
      "Those wings are made of thousands of tiny scales? You're not fragile. You're a mosaic masterpiece. Every setback that knocked a scale loose just made room for the light to shine through differently.",
      "Caterpillar eating everything in sight? That's not gluttony, love. That's preparation. You can't transform on an empty stomach. Sometimes growth looks like demolishing a salad bar with purpose.",
      "Currently dissolving into caterpillar soup inside your chrysalis? Congratulations, you're not falling apart. You're becoming. The goo phase isn't failure; it's your ingredients rearranging into fabulous.",
      "Butterfly holding wings up like victory flags, or moth wrapping them like a cozy cloak? Both valid. Some transformations demand applause; others whisper their magnificence. You choose your reveal.",
      "Night moth attracted to flames? That's not self-destructive. That's knowing that sometimes the most beautiful things require a little danger. You're not reckless; you're radically committed to the light.",
      "Spent weeks as a chrysalis hanging upside down? That's not wasted time. That's marinating in possibility. Good things come to those who wait... while completely liquefied. Trust the process.",
      "Butterfly by day, or moth by night? Why choose? You're proof that beauty doesn't require a specific schedule. Some flowers bloom in sunshine, some in moonlight. Both feed souls.",
      "Your scales create colors that don't even exist as pigments? You're not just colorful. You're bending light itself to express yourself. That's not decoration; that's physics with style.",
      "Metamorphosis making you unrecognizable from your caterpillar days? Perfect. You're not losing yourself. You're revealing what was always encoded in your DNA. The wings were always there, waiting.",
      "Silk moth spinning your own cocoon? You're not isolating. You're creating a custom transformation chamber. Some use nature's chrysalis; you're DIY-ing your glow-up. Respect.",
      "Feeling neither caterpillar nor butterfly? You're in the sacred soup phase, darling. Not every moment of becoming needs to be Instagram-worthy. Sometimes magic looks like mush.",
      "Your caterpillar self wouldn't recognize your butterfly self? Good. That's not identity crisis. That's the whole point. Imagine explaining wings to your former earthbound self. Some changes can't be predicted, only lived.",
      "Skipper butterfly can't decide if you're moth or butterfly? You're not confused. You're category-defying. Why be one thing when you can be a beautiful question mark with wings?",
      "Moths navigating by moonlight since before humans invented maps? You're not lost in the dark. You're following celestial guidance. Your compass is older than consciousness.",
      "Those wings that seemed impossible when you were crawling? They were always part of the plan, encoded in every bite of leaf you took. You weren't just eating. You were building your escape velocity. Now fly, you magnificent transformation story. The world needs your particular pattern of light."
    ]
  }
};
